### ISSUE TITLE
Feature NTP

### ISSUE THREAD

**Issue by dminguezp** [febalci/seismoM5#11]
Hello, I have tried your project and it seems incredible, I think it could only be improved by adding a simple feature. In the world of seismology, a data that is very important is time. I think that if synchronization with an NTP time server could be added and when sending the data via mqtt the timestamp was added, the device could be used for seismological purposes to study seismicity.
Thank you in advance for the fantastic work you have done with your project.

**Comment by febalci** [comment]
Thanks @dminguezp, you are absolutely right; and a second solution could be to use NTP synchronization of the MQTT or the host server, so that whenever MQTT server receives an earthquake signal; the host will use its own synced time. I use it this way at the moment.
